language: scala
sudo: false
scala:
 - 2.11.7

# Play 2.5.0 requires Java 8
jdk:
 - oraclejdk8

script:
 - sbt +test
 - sbt "set version += \"-SNAPSHOT\"" +publishLocal scripted

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache